version: "3"
services: 
  mongodb_test:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testPassword
    ports:
      - "27018:27017"